# Generated by Django 3.0.8 on 2020-08-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug_mate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementsbonus',
            name='cum_savings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
