# Generated by Django 3.0.8 on 2020-08-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plug_mate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meters',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meter_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'meters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PowerEnergyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unix_time', models.BigIntegerField()),
                ('energy', models.FloatField()),
                ('power', models.FloatField()),
                ('device_state', models.IntegerField()),
                ('device_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'power_energy_consumption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('unix_time', models.BigIntegerField()),
                ('rssi', models.FloatField()),
                ('presence', models.IntegerField()),
            ],
            options={
                'db_table': 'presence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_id_field',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id_profile', to='plug_mate_app.Users'),
            preserve_default=False,
        ),
    ]
