# Generated by Django 3.0.8 on 2020-08-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug_mate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tree_first', models.BooleanField()),
                ('tree_fifth', models.BooleanField()),
                ('redeem_reward', models.BooleanField()),
                ('first_remote', models.BooleanField()),
                ('first_schedule', models.BooleanField()),
                ('first_presence', models.BooleanField()),
            ],
            options={
                'db_table': 'achievements_bonus',
            },
        ),
    ]
