# Generated by Django 3.0.8 on 2020-08-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug_mate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceBasedControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_state', models.BinaryField()),
                ('off_after', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RemoteControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_state', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBasedControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100)),
            ],
        ),
    ]
