# Generated by Django 3.0.8 on 2020-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug_mate_app', '0002_achievementsbonus_presencedata_remotedata_scheduledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementsbonus',
            name='tree_tenth',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
