# Generated by Django 3.0.8 on 2020-08-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug_mate_app', '0003_auto_20200809_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cost_saving', models.IntegerField()),
                ('schedule_based', models.IntegerField()),
                ('complete_daily', models.IntegerField()),
                ('complete_weekly', models.IntegerField()),
            ],
            options={
                'db_table': 'achievements_weekly',
            },
        ),
        migrations.CreateModel(
            name='PresenceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_type', models.CharField(max_length=100)),
                ('presence_setting', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RemoteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_type', models.CharField(max_length=100)),
                ('device_state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('event_start', models.CharField(max_length=100)),
                ('event_end', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('event_rrule', models.CharField(max_length=100)),
                ('device_type_id', models.IntegerField()),
                ('device_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='achievementsbonus',
            name='first_presence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievementsbonus',
            name='first_remote',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievementsbonus',
            name='first_schedule',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievementsbonus',
            name='redeem_reward',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievementsbonus',
            name='tree_fifth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievementsbonus',
            name='tree_first',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievementsbonus',
            name='tree_tenth',
            field=models.IntegerField(),
        ),
    ]
